#!/bin/bash
# /etc/init.d/netcharger

### BEGIN INIT INFO
# Provides:          netcharger
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to connect a charger to internet
### END INIT INFO


case "$1" in 
    start)
        echo "Starting NetCharger"
        /home/pi/networkcharger/chargerd
        ;;
    stop)
        echo "Stopping netcharger"
        killall chargerd
        ;;
    *)
        echo "Usage: /etc/init.d/netcharger start|stop"
        exit 1
        ;;
esac

exit 0
